name: dotrun
base: core18
version: '1.0.0-rc1'
summary: A command-line tool for running projects
description: |
  A command-line tool for running projects

grade: stable
confinement: devmode

parts:
  node:
    plugin: dump
    source: https://deb.nodesource.com/node_12.x/pool/main/n/nodejs/nodejs_12.4.0-1nodesource1_amd64.deb

  yarn:
    plugin: dump
    source: https://github.com/yarnpkg/yarn/releases/download/v1.16.0/yarn_1.16.0_all.deb

  dotrun-module:
    plugin: python
    stage-packages:
      - python3-pip
      - python3-dev
      - curl
      - build-essential
      - libpq-dev
      - libsodium-dev
      - libjpeg-dev
      - zlib1g-dev
      - libpng-dev
      - libmagickwand-dev
      - libjpeg-progs
      - optipng
      - bundler
    source: .

apps:
  dotrun:
    command: dotrun
    plugs:
      - home
      - network
      - network-bind
      - process-control
    environment:
      LC_ALL: C.UTF-8
